language: python
python:
    - "2.7"
    - "2.6"

env:
    - DJANGO=1.4.3
    - DJANGO=1.3.5
    - DJANGO=https://github.com/django/django/zipball/master

install:
    - pip install -q Django==$DJANGO --use-mirrors

script: python setup.py test

notifications:
    email:
        recipients:
            - code@pixelatedninja.com