language: python
python:
    - "2.7"
    - "2.6"

env:
    - DJANGO=1.4.3
    - DJANGO=1.3.5

install:
    - pip install -q Django==$DJANGO --use-mirrors
    - pip install pep8
    - pip install pyflakes

before_script:
    - "pep8 --exclude=migrations --ignore=E501,E225 mcfeely"
    - "pyflakes mcfeely || :"

script: python setup.py test

notifications:
    email:
        recipients:
            - code@pixelatedninja.com
