language: python
python:
    - 2.7
    - 2.6
    - 3.2
    - 3.3

env:
    - DJANGO_VERSION=DJANGO==1.4.5
    - DJANGO_VERSION=DJANGO==1.7
    - DJANGO_VERSION=DJANGO==1.8

matrix:
    exclude:
        - python: 3.2
          env: DJANGO_VERSION=DJANGO==1.4.5
        - python: 3.3
          env: DJANGO_VERSION=DJANGO==1.4.5
        - python: 2.6
          env: DJANGO_VERSION=DJANGO==1.7
        - python: 2.6
          env: DJANGO_VERSION=DJANGO==1.8


install:
    - pip install -q $DJANGO_VERSION --use-mirrors

before_script:
    - pip install coveralls --use-mirrors

script: 
    coverage run --source=mcfeely setup.py test

after_success:
    coveralls

