language: python
python:
    - "2.7"
    - "2.6"

env:
    - DJANGO_VERSION=DJANGO==1.4.3
    - DJANGO_VERSION=DJANGO==1.3.5
    - DJANGO_VERSION=git+git://github.com/django/django.git

install:
    - pip install -q $DJANGO_VERSION --use-mirrors

script: python setup.py test

notifications:
    email:
        recipients:
            - code@pixelatedninja.com