language: python
python:
    - 2.6
    - 2.7
    - 3.3
    - 3.4
    - 3.5

env:
    - DJANGO_VERSION=DJANGO==1.7
    - DJANGO_VERSION=DJANGO==1.8
    - DJANGO_VERSION=DJANGO==1.9

matrix:
    exclude:
        - python: 2.6
          env: DJANGO_VERSION=DJANGO==1.7
        - python: 3.5
          env: DJANGO_VERSION=DJANGO==1.7
        - python: 2.6
          env: DJANGO_VERSION=DJANGO==1.8
        - python: 2.6
          env: DJANGO_VERSION=DJANGO==1.9
        - python: 3.3
          env: DJANGO_VERSION=DJANGO==1.9


install:
    - pip install -q $DJANGO_VERSION
    - if [ "$TRAVIS_PYTHON_VERSION" == "3.2" ]; then travis_retry pip install coverage==3.7.1; fi
    - if [ "$TRAVIS_PYTHON_VERSION" != "3.2" ]; then travis_retry pip install coverage; fi
    - pip install coveralls

script: 
    coverage run --source=mcfeely setup.py test

after_success:
    coveralls

