language: python
python:
    - "2.7"

env:
    - DJANGO=1.4.3

install:
    - pip install -q Django==$DJANGO --use-mirrors

script: python setup.py test

notifications:
    email:
        recipients:
            - code@pixelatedninja.com