language: python
python:
    - 2.7
    - 2.6
    - 3.2

env:
    - DJANGO_VERSION=DJANGO==1.4.5
    - DJANGO_VERSION=DJANGO==1.3.7
    - DJANGO_VERSION=DJANGO==1.5

matrix:
    exclude:
        - python: 3.2
          env: DJANGO_VERSION=DJANGO==1.4.5
        - python: 3.2
          env: DJANGO_VERSION=DJANGO==1.3.7

install:
    - pip install -q $DJANGO_VERSION --use-mirrors

script: python setup.py test

notifications:
    email:
        recipients:
            - code@pixelatedninja.com